# Generated by Django 5.0.6 on 2024-05-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='registration_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='registration_user_permissions_set', to='auth.permission'),
        ),
    ]
